# Generated by Django 5.0.3 on 2024-03-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=14)),
                ('mail', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=24)),
                ('isntagram', models.CharField(max_length=24)),
                ('telegram', models.CharField(max_length=28)),
            ],
        ),
    ]
