# Generated by Django 5.0.3 on 2024-03-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_alter_footer_isntagram_alter_footer_telegram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='isntagram',
            new_name='instagram',
        ),
    ]
