# Generated by Django 5.0.3 on 2024-03-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0004_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phone',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mail',
            field=models.EmailField(blank=True, default='a', max_length=254),
        ),
    ]
